### ISSUE TITLE
【建议】建议增加总计

### ISSUE THREAD

**Issue by VistaQvQ** [telppa/KMCounter#4]
建议有个输入总计，所有输入的统计结果计数更新到ini中。

**Comment by telppa** [comment]
退出程序再看看？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/KMCounter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 中午11:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/KMCounter] 【建议】建议增加总计 (#4)





 
建议有个输入总计，所有输入的统计结果计数更新到ini中。

**Comment by VistaQvQ** [comment]
> 退出程序再看看？
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "telppa/KMCounter"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2021年3月18日(星期四) 中午11:21
> ***@***.***&gt;;
> ***@***.***&gt;;
> 主题:&nbsp;[telppa/KMCounter] 【建议】建议增加总计 (#4)
> 
> 
> 
> 
> 
>  
> 建议有个输入总计，所有输入的统计结果计数更新到ini中。
>  
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

准确的说应该是，在热力图中显示近期所有输入的热力结果

**Comment by telppa** [comment]
下个版本增加此功能。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vista ***@***.***&gt;; 
发送时间: 2021年3月19日(星期五) 上午8:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [telppa/KMCounter] 【建议】建议增加总计 (#4)





  
退出程序再看看？
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "telppa/KMCounter"                                                                                    @.&gt;;
 发送时间:&nbsp;2021年3月18日(星期四) 中午11:21
 @.&gt;;
 @.***&gt;;
 主题:&nbsp;[telppa/KMCounter] 【建议】建议增加总计 (#4)
 
建议有个输入总计，所有输入的统计结果计数更新到ini中。
 
—
 You are receiving this because you are subscribed to this thread.
 Reply to this email directly, view it on GitHub, or unsubscribe.
  
准确的说应该是，在热力图中显示近期所有输入的热力结果
